using UnityEngine;

/**
 * Impact zone generated by a missile
 * Works like a force shield destroying asteroids that hit it
 */
public class ImpactZone : MonoBehaviour
{
    [Header("Amount that shield scales for each interval")]
    [SerializeField] private float scaleStep = 0.2f;
    [Header("Time interval that shields scales")]
    [SerializeField] private float scaleInterval = 0.1f;
    [Header("Max shield duration")]
    [SerializeField] private float duration = 10f;
    
    private float _timeElapsed;
    private float _currentScale = 1;
    private float _nextScale;
    
    
    // Update is called once per frame
    void Update()
    {
        //Increments time elapsed
        _timeElapsed += Time.deltaTime;
        
        if(_timeElapsed > duration)
        {
            //Destroy shield case duration ends
            Destroy(gameObject);
        }
        
        MagnifyImpactZone();
    }
    
    /**
     * Step the scale of Impact Zone 
     */
    private void MagnifyImpactZone()
    {
        if (!(_timeElapsed > _nextScale)) return;
        
        transform.localScale = new Vector3(_currentScale, _currentScale,_currentScale);
        _currentScale+=scaleStep + Time.deltaTime;
        _nextScale += scaleInterval;
    }
}
